<?php
/**
 * WyszukiwanieNadanychUprawnieApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * KSeF API TE
 *
 * **Wersja API:** 2.0.0 (build 2.0.0-rc2-te-20250725.2+5adfde843e2c34f7d63e9a50dccbb9dab79bc320)<br>  **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br>  **Historia zmian:** [Changelog](#)<br>  **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 * The version of the OpenAPI document: v2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * WyszukiwanieNadanychUprawnieApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WyszukiwanieNadanychUprawnieApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV2PermissionsQueryAuthorizationsGrantsPost' => [
            'application/json',
        ],
        'apiV2PermissionsQueryEntitiesRolesGet' => [
            'application/json',
        ],
        'apiV2PermissionsQueryEuEntitiesGrantsPost' => [
            'application/json',
        ],
        'apiV2PermissionsQueryPersonsGrantsPost' => [
            'application/json',
        ],
        'apiV2PermissionsQuerySubordinateEntitiesRolesPost' => [
            'application/json',
        ],
        'apiV2PermissionsQuerySubunitsGrantsPost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV2PermissionsQueryAuthorizationsGrantsPost
     *
     * Pobranie listy uprawnień podmiotowych do obsługi faktur
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\EntityAuthorizationPermissionsQueryRequest|null $entity_authorization_permissions_query_request entity_authorization_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryAuthorizationsGrantsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\QueryEntityAuthorizationPermissionsResponse|\OpenAPI\Client\Model\ExceptionResponse
     */
    public function apiV2PermissionsQueryAuthorizationsGrantsPost($page_offset = null, $page_size = null, $entity_authorization_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryAuthorizationsGrantsPost'][0])
    {
        list($response) = $this->apiV2PermissionsQueryAuthorizationsGrantsPostWithHttpInfo($page_offset, $page_size, $entity_authorization_permissions_query_request, $contentType);
        return $response;
    }

    /**
     * Operation apiV2PermissionsQueryAuthorizationsGrantsPostWithHttpInfo
     *
     * Pobranie listy uprawnień podmiotowych do obsługi faktur
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\EntityAuthorizationPermissionsQueryRequest|null $entity_authorization_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryAuthorizationsGrantsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\QueryEntityAuthorizationPermissionsResponse|\OpenAPI\Client\Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2PermissionsQueryAuthorizationsGrantsPostWithHttpInfo($page_offset = null, $page_size = null, $entity_authorization_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryAuthorizationsGrantsPost'][0])
    {
        $request = $this->apiV2PermissionsQueryAuthorizationsGrantsPostRequest($page_offset, $page_size, $entity_authorization_permissions_query_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\QueryEntityAuthorizationPermissionsResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\QueryEntityAuthorizationPermissionsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\QueryEntityAuthorizationPermissionsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV2PermissionsQueryAuthorizationsGrantsPostAsync
     *
     * Pobranie listy uprawnień podmiotowych do obsługi faktur
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\EntityAuthorizationPermissionsQueryRequest|null $entity_authorization_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryAuthorizationsGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQueryAuthorizationsGrantsPostAsync($page_offset = null, $page_size = null, $entity_authorization_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryAuthorizationsGrantsPost'][0])
    {
        return $this->apiV2PermissionsQueryAuthorizationsGrantsPostAsyncWithHttpInfo($page_offset, $page_size, $entity_authorization_permissions_query_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2PermissionsQueryAuthorizationsGrantsPostAsyncWithHttpInfo
     *
     * Pobranie listy uprawnień podmiotowych do obsługi faktur
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\EntityAuthorizationPermissionsQueryRequest|null $entity_authorization_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryAuthorizationsGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQueryAuthorizationsGrantsPostAsyncWithHttpInfo($page_offset = null, $page_size = null, $entity_authorization_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryAuthorizationsGrantsPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\QueryEntityAuthorizationPermissionsResponse';
        $request = $this->apiV2PermissionsQueryAuthorizationsGrantsPostRequest($page_offset, $page_size, $entity_authorization_permissions_query_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2PermissionsQueryAuthorizationsGrantsPost'
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\EntityAuthorizationPermissionsQueryRequest|null $entity_authorization_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryAuthorizationsGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2PermissionsQueryAuthorizationsGrantsPostRequest($page_offset = null, $page_size = null, $entity_authorization_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryAuthorizationsGrantsPost'][0])
    {





        $resourcePath = '/api/v2/permissions/query/authorizations/grants';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_offset,
            'pageOffset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($entity_authorization_permissions_query_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($entity_authorization_permissions_query_request));
            } else {
                $httpBody = $entity_authorization_permissions_query_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2PermissionsQueryEntitiesRolesGet
     *
     * Pobranie listy ról podmiotu
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryEntitiesRolesGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\QueryEntityRolesResponse|\OpenAPI\Client\Model\ExceptionResponse
     */
    public function apiV2PermissionsQueryEntitiesRolesGet($page_offset = null, $page_size = null, string $contentType = self::contentTypes['apiV2PermissionsQueryEntitiesRolesGet'][0])
    {
        list($response) = $this->apiV2PermissionsQueryEntitiesRolesGetWithHttpInfo($page_offset, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation apiV2PermissionsQueryEntitiesRolesGetWithHttpInfo
     *
     * Pobranie listy ról podmiotu
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryEntitiesRolesGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\QueryEntityRolesResponse|\OpenAPI\Client\Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2PermissionsQueryEntitiesRolesGetWithHttpInfo($page_offset = null, $page_size = null, string $contentType = self::contentTypes['apiV2PermissionsQueryEntitiesRolesGet'][0])
    {
        $request = $this->apiV2PermissionsQueryEntitiesRolesGetRequest($page_offset, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\QueryEntityRolesResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\QueryEntityRolesResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\QueryEntityRolesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV2PermissionsQueryEntitiesRolesGetAsync
     *
     * Pobranie listy ról podmiotu
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryEntitiesRolesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQueryEntitiesRolesGetAsync($page_offset = null, $page_size = null, string $contentType = self::contentTypes['apiV2PermissionsQueryEntitiesRolesGet'][0])
    {
        return $this->apiV2PermissionsQueryEntitiesRolesGetAsyncWithHttpInfo($page_offset, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2PermissionsQueryEntitiesRolesGetAsyncWithHttpInfo
     *
     * Pobranie listy ról podmiotu
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryEntitiesRolesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQueryEntitiesRolesGetAsyncWithHttpInfo($page_offset = null, $page_size = null, string $contentType = self::contentTypes['apiV2PermissionsQueryEntitiesRolesGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\QueryEntityRolesResponse';
        $request = $this->apiV2PermissionsQueryEntitiesRolesGetRequest($page_offset, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2PermissionsQueryEntitiesRolesGet'
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryEntitiesRolesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2PermissionsQueryEntitiesRolesGetRequest($page_offset = null, $page_size = null, string $contentType = self::contentTypes['apiV2PermissionsQueryEntitiesRolesGet'][0])
    {




        $resourcePath = '/api/v2/permissions/query/entities/roles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_offset,
            'pageOffset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2PermissionsQueryEuEntitiesGrantsPost
     *
     * Pobranie listy uprawnień administratorów lub reprezentantów podmiotów unijnych uprawnionych do samofakturowania
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\EuEntityPermissionsQueryRequest|null $eu_entity_permissions_query_request eu_entity_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryEuEntitiesGrantsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\QueryEuEntityPermissionsResponse|\OpenAPI\Client\Model\ExceptionResponse
     */
    public function apiV2PermissionsQueryEuEntitiesGrantsPost($page_offset = null, $page_size = null, $eu_entity_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryEuEntitiesGrantsPost'][0])
    {
        list($response) = $this->apiV2PermissionsQueryEuEntitiesGrantsPostWithHttpInfo($page_offset, $page_size, $eu_entity_permissions_query_request, $contentType);
        return $response;
    }

    /**
     * Operation apiV2PermissionsQueryEuEntitiesGrantsPostWithHttpInfo
     *
     * Pobranie listy uprawnień administratorów lub reprezentantów podmiotów unijnych uprawnionych do samofakturowania
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\EuEntityPermissionsQueryRequest|null $eu_entity_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryEuEntitiesGrantsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\QueryEuEntityPermissionsResponse|\OpenAPI\Client\Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2PermissionsQueryEuEntitiesGrantsPostWithHttpInfo($page_offset = null, $page_size = null, $eu_entity_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryEuEntitiesGrantsPost'][0])
    {
        $request = $this->apiV2PermissionsQueryEuEntitiesGrantsPostRequest($page_offset, $page_size, $eu_entity_permissions_query_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\QueryEuEntityPermissionsResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\QueryEuEntityPermissionsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\QueryEuEntityPermissionsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV2PermissionsQueryEuEntitiesGrantsPostAsync
     *
     * Pobranie listy uprawnień administratorów lub reprezentantów podmiotów unijnych uprawnionych do samofakturowania
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\EuEntityPermissionsQueryRequest|null $eu_entity_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryEuEntitiesGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQueryEuEntitiesGrantsPostAsync($page_offset = null, $page_size = null, $eu_entity_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryEuEntitiesGrantsPost'][0])
    {
        return $this->apiV2PermissionsQueryEuEntitiesGrantsPostAsyncWithHttpInfo($page_offset, $page_size, $eu_entity_permissions_query_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2PermissionsQueryEuEntitiesGrantsPostAsyncWithHttpInfo
     *
     * Pobranie listy uprawnień administratorów lub reprezentantów podmiotów unijnych uprawnionych do samofakturowania
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\EuEntityPermissionsQueryRequest|null $eu_entity_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryEuEntitiesGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQueryEuEntitiesGrantsPostAsyncWithHttpInfo($page_offset = null, $page_size = null, $eu_entity_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryEuEntitiesGrantsPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\QueryEuEntityPermissionsResponse';
        $request = $this->apiV2PermissionsQueryEuEntitiesGrantsPostRequest($page_offset, $page_size, $eu_entity_permissions_query_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2PermissionsQueryEuEntitiesGrantsPost'
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\EuEntityPermissionsQueryRequest|null $eu_entity_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryEuEntitiesGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2PermissionsQueryEuEntitiesGrantsPostRequest($page_offset = null, $page_size = null, $eu_entity_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryEuEntitiesGrantsPost'][0])
    {





        $resourcePath = '/api/v2/permissions/query/eu-entities/grants';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_offset,
            'pageOffset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($eu_entity_permissions_query_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($eu_entity_permissions_query_request));
            } else {
                $httpBody = $eu_entity_permissions_query_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2PermissionsQueryPersonsGrantsPost
     *
     * Pobranie listy uprawnień do pracy w KSeF nadanych osobom fizycznym lub podmiotom
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\PersonPermissionsQueryRequest|null $person_permissions_query_request person_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryPersonsGrantsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\QueryPersonPermissionsResponse|\OpenAPI\Client\Model\ExceptionResponse
     */
    public function apiV2PermissionsQueryPersonsGrantsPost($page_offset = null, $page_size = null, $person_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryPersonsGrantsPost'][0])
    {
        list($response) = $this->apiV2PermissionsQueryPersonsGrantsPostWithHttpInfo($page_offset, $page_size, $person_permissions_query_request, $contentType);
        return $response;
    }

    /**
     * Operation apiV2PermissionsQueryPersonsGrantsPostWithHttpInfo
     *
     * Pobranie listy uprawnień do pracy w KSeF nadanych osobom fizycznym lub podmiotom
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\PersonPermissionsQueryRequest|null $person_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryPersonsGrantsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\QueryPersonPermissionsResponse|\OpenAPI\Client\Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2PermissionsQueryPersonsGrantsPostWithHttpInfo($page_offset = null, $page_size = null, $person_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryPersonsGrantsPost'][0])
    {
        $request = $this->apiV2PermissionsQueryPersonsGrantsPostRequest($page_offset, $page_size, $person_permissions_query_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\QueryPersonPermissionsResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\QueryPersonPermissionsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\QueryPersonPermissionsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV2PermissionsQueryPersonsGrantsPostAsync
     *
     * Pobranie listy uprawnień do pracy w KSeF nadanych osobom fizycznym lub podmiotom
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\PersonPermissionsQueryRequest|null $person_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryPersonsGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQueryPersonsGrantsPostAsync($page_offset = null, $page_size = null, $person_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryPersonsGrantsPost'][0])
    {
        return $this->apiV2PermissionsQueryPersonsGrantsPostAsyncWithHttpInfo($page_offset, $page_size, $person_permissions_query_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2PermissionsQueryPersonsGrantsPostAsyncWithHttpInfo
     *
     * Pobranie listy uprawnień do pracy w KSeF nadanych osobom fizycznym lub podmiotom
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\PersonPermissionsQueryRequest|null $person_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryPersonsGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQueryPersonsGrantsPostAsyncWithHttpInfo($page_offset = null, $page_size = null, $person_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryPersonsGrantsPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\QueryPersonPermissionsResponse';
        $request = $this->apiV2PermissionsQueryPersonsGrantsPostRequest($page_offset, $page_size, $person_permissions_query_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2PermissionsQueryPersonsGrantsPost'
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\PersonPermissionsQueryRequest|null $person_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQueryPersonsGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2PermissionsQueryPersonsGrantsPostRequest($page_offset = null, $page_size = null, $person_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQueryPersonsGrantsPost'][0])
    {





        $resourcePath = '/api/v2/permissions/query/persons/grants';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_offset,
            'pageOffset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($person_permissions_query_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($person_permissions_query_request));
            } else {
                $httpBody = $person_permissions_query_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2PermissionsQuerySubordinateEntitiesRolesPost
     *
     * Pobranie listy podmiotów podrzędnych
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\SubordinateEntityRolesQueryRequest|null $subordinate_entity_roles_query_request subordinate_entity_roles_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQuerySubordinateEntitiesRolesPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\QuerySubordinateEntityRolesResponse|\OpenAPI\Client\Model\ExceptionResponse
     */
    public function apiV2PermissionsQuerySubordinateEntitiesRolesPost($page_offset = null, $page_size = null, $subordinate_entity_roles_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQuerySubordinateEntitiesRolesPost'][0])
    {
        list($response) = $this->apiV2PermissionsQuerySubordinateEntitiesRolesPostWithHttpInfo($page_offset, $page_size, $subordinate_entity_roles_query_request, $contentType);
        return $response;
    }

    /**
     * Operation apiV2PermissionsQuerySubordinateEntitiesRolesPostWithHttpInfo
     *
     * Pobranie listy podmiotów podrzędnych
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\SubordinateEntityRolesQueryRequest|null $subordinate_entity_roles_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQuerySubordinateEntitiesRolesPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\QuerySubordinateEntityRolesResponse|\OpenAPI\Client\Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2PermissionsQuerySubordinateEntitiesRolesPostWithHttpInfo($page_offset = null, $page_size = null, $subordinate_entity_roles_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQuerySubordinateEntitiesRolesPost'][0])
    {
        $request = $this->apiV2PermissionsQuerySubordinateEntitiesRolesPostRequest($page_offset, $page_size, $subordinate_entity_roles_query_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\QuerySubordinateEntityRolesResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\QuerySubordinateEntityRolesResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\QuerySubordinateEntityRolesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV2PermissionsQuerySubordinateEntitiesRolesPostAsync
     *
     * Pobranie listy podmiotów podrzędnych
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\SubordinateEntityRolesQueryRequest|null $subordinate_entity_roles_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQuerySubordinateEntitiesRolesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQuerySubordinateEntitiesRolesPostAsync($page_offset = null, $page_size = null, $subordinate_entity_roles_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQuerySubordinateEntitiesRolesPost'][0])
    {
        return $this->apiV2PermissionsQuerySubordinateEntitiesRolesPostAsyncWithHttpInfo($page_offset, $page_size, $subordinate_entity_roles_query_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2PermissionsQuerySubordinateEntitiesRolesPostAsyncWithHttpInfo
     *
     * Pobranie listy podmiotów podrzędnych
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\SubordinateEntityRolesQueryRequest|null $subordinate_entity_roles_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQuerySubordinateEntitiesRolesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQuerySubordinateEntitiesRolesPostAsyncWithHttpInfo($page_offset = null, $page_size = null, $subordinate_entity_roles_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQuerySubordinateEntitiesRolesPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\QuerySubordinateEntityRolesResponse';
        $request = $this->apiV2PermissionsQuerySubordinateEntitiesRolesPostRequest($page_offset, $page_size, $subordinate_entity_roles_query_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2PermissionsQuerySubordinateEntitiesRolesPost'
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\SubordinateEntityRolesQueryRequest|null $subordinate_entity_roles_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQuerySubordinateEntitiesRolesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2PermissionsQuerySubordinateEntitiesRolesPostRequest($page_offset = null, $page_size = null, $subordinate_entity_roles_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQuerySubordinateEntitiesRolesPost'][0])
    {





        $resourcePath = '/api/v2/permissions/query/subordinate-entities/roles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_offset,
            'pageOffset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($subordinate_entity_roles_query_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($subordinate_entity_roles_query_request));
            } else {
                $httpBody = $subordinate_entity_roles_query_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV2PermissionsQuerySubunitsGrantsPost
     *
     * Pobranie listy uprawnień administratorów jednostek i podmiotów podrzędnych
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\SubunitPermissionsQueryRequest|null $subunit_permissions_query_request subunit_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQuerySubunitsGrantsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\QuerySubunitPermissionsResponse|\OpenAPI\Client\Model\ExceptionResponse
     */
    public function apiV2PermissionsQuerySubunitsGrantsPost($page_offset = null, $page_size = null, $subunit_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQuerySubunitsGrantsPost'][0])
    {
        list($response) = $this->apiV2PermissionsQuerySubunitsGrantsPostWithHttpInfo($page_offset, $page_size, $subunit_permissions_query_request, $contentType);
        return $response;
    }

    /**
     * Operation apiV2PermissionsQuerySubunitsGrantsPostWithHttpInfo
     *
     * Pobranie listy uprawnień administratorów jednostek i podmiotów podrzędnych
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\SubunitPermissionsQueryRequest|null $subunit_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQuerySubunitsGrantsPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\QuerySubunitPermissionsResponse|\OpenAPI\Client\Model\ExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV2PermissionsQuerySubunitsGrantsPostWithHttpInfo($page_offset = null, $page_size = null, $subunit_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQuerySubunitsGrantsPost'][0])
    {
        $request = $this->apiV2PermissionsQuerySubunitsGrantsPostRequest($page_offset, $page_size, $subunit_permissions_query_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\QuerySubunitPermissionsResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\QuerySubunitPermissionsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\QuerySubunitPermissionsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV2PermissionsQuerySubunitsGrantsPostAsync
     *
     * Pobranie listy uprawnień administratorów jednostek i podmiotów podrzędnych
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\SubunitPermissionsQueryRequest|null $subunit_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQuerySubunitsGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQuerySubunitsGrantsPostAsync($page_offset = null, $page_size = null, $subunit_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQuerySubunitsGrantsPost'][0])
    {
        return $this->apiV2PermissionsQuerySubunitsGrantsPostAsyncWithHttpInfo($page_offset, $page_size, $subunit_permissions_query_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV2PermissionsQuerySubunitsGrantsPostAsyncWithHttpInfo
     *
     * Pobranie listy uprawnień administratorów jednostek i podmiotów podrzędnych
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\SubunitPermissionsQueryRequest|null $subunit_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQuerySubunitsGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV2PermissionsQuerySubunitsGrantsPostAsyncWithHttpInfo($page_offset = null, $page_size = null, $subunit_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQuerySubunitsGrantsPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\QuerySubunitPermissionsResponse';
        $request = $this->apiV2PermissionsQuerySubunitsGrantsPostRequest($page_offset, $page_size, $subunit_permissions_query_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV2PermissionsQuerySubunitsGrantsPost'
     *
     * @param  int|null $page_offset Numer strony wyników. (optional)
     * @param  int|null $page_size Rozmiar strony wyników. (optional)
     * @param  \OpenAPI\Client\Model\SubunitPermissionsQueryRequest|null $subunit_permissions_query_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV2PermissionsQuerySubunitsGrantsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV2PermissionsQuerySubunitsGrantsPostRequest($page_offset = null, $page_size = null, $subunit_permissions_query_request = null, string $contentType = self::contentTypes['apiV2PermissionsQuerySubunitsGrantsPost'][0])
    {





        $resourcePath = '/api/v2/permissions/query/subunits/grants';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_offset,
            'pageOffset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($subunit_permissions_query_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($subunit_permissions_query_request));
            } else {
                $httpBody = $subunit_permissions_query_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
